
<div id="Hydrogène"><?php $post = affichage(1);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Hélium"><?php $post = affichage(2);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Lithium"><?php $post = affichage(3);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Béryllium"><?php $post = affichage(4);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Bore"><?php $post = affichage(5);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Carbone"><?php $post = affichage(6);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Azote"><?php $post = affichage(7);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Oxygène"><?php $post = affichage(8);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Fluor"><?php $post = affichage(9);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Néon"><?php $post = affichage(10);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Sodium"><?php $post = affichage(11);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Magnésium"><?php $post = affichage(12);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Aluminium"><?php $post = affichage(13);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Silicium"><?php $post = affichage(14);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Phosphore"><?php $post = affichage(15);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Soufre"><?php $post = affichage(16);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Chlore"><?php $post = affichage(17);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Argon"><?php $post = affichage(18);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Potassium"><?php $post = affichage(19);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Calcium"><?php $post = affichage(20);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Scandium"><?php $post = affichage(21);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Titane"><?php $post = affichage(22);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Vanadium"><?php $post = affichage(23);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Chrome"><?php $post = affichage(24);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Manganèse"><?php $post = affichage(25);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Fer"><?php $post = affichage(26);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Cobalt"><?php $post = affichage(27);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Nickel"><?php $post = affichage(28);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Cuivre"><?php $post = affichage(29);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Zinc"><?php $post = affichage(30);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Gallium"><?php $post = affichage(31);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Germanium"><?php $post = affichage(32);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Arsenic"><?php $post = affichage(33);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Sélénium"><?php $post = affichage(34);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Brome"><?php $post = affichage(35);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Krypton"><?php $post = affichage(36);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Rubidium"><?php $post = affichage(37);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Strontium"><?php $post = affichage(38);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Yttrium"><?php $post = affichage(39);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Zirconium"><?php $post = affichage(40);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Niobium"><?php $post = affichage(41);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Molybdène"><?php $post = affichage(42);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Technétium"><?php $post = affichage(43);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Ruthénium"><?php $post = affichage(44);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Rhodium"><?php $post = affichage(45);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Palladium"><?php $post = affichage(46);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Argent"><?php $post = affichage(47);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Cadmium"><?php $post = affichage(48);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Indium"><?php $post = affichage(49);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Étain"><?php $post = affichage(50);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Antimoine"><?php $post = affichage(51);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Tellure"><?php $post = affichage(52);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Iode"><?php $post = affichage(53);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Xénon"><?php $post = affichage(54);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Césium"><?php $post = affichage(55);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Baryum"><?php $post = affichage(56);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Lanthane"><?php $post = affichage(57);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Cérium"><?php $post = affichage(58);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Praséodyme"><?php $post = affichage(59);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Néodyme"><?php $post = affichage(60);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Prométhium"><?php $post = affichage(61);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Samarium"><?php $post = affichage(62);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Europium"><?php $post = affichage(63);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Gadolinium"><?php $post = affichage(64);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Terbium"><?php $post = affichage(65);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Dysprosium"><?php $post = affichage(66);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Holmium"><?php $post = affichage(67);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Erbium"><?php $post = affichage(68);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Thulium"><?php $post = affichage(69);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Ytterbium"><?php $post = affichage(70);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Lutécium"><?php $post = affichage(71);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Hafnium"><?php $post = affichage(72);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Tantale"><?php $post = affichage(73);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Tungstène"><?php $post = affichage(74);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Rhénium"><?php $post = affichage(75);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Osmium"><?php $post = affichage(76);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Iridium"><?php $post = affichage(77);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Platine"><?php $post = affichage(78);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Or"><?php $post = affichage(79);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Mercure"><?php $post = affichage(80);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Thallium"><?php $post = affichage(81);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Plomb"><?php $post = affichage(82);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Bismuth"><?php $post = affichage(83);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Polonium"><?php $post = affichage(84);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Astate"><?php $post = affichage(85);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Radon"><?php $post = affichage(86);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Francium"><?php $post = affichage(87);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Radium"><?php $post = affichage(88);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Actinium"><?php $post = affichage(89);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Thorium"><?php $post = affichage(90);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Protactinium"><?php $post = affichage(91);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Uranium"><?php $post = affichage(92);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Neptunium"><?php $post = affichage(93);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Plutonium"><?php $post = affichage(94);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Américium"><?php $post = affichage(95);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Curium"><?php $post = affichage(96);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Berkélium"><?php $post = affichage(97);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Californium"><?php $post = affichage(98);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Einsteinium"><?php $post = affichage(99);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Fermium"><?php $post = affichage(100);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Mendélévium"><?php $post = affichage(101);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Nobélium"><?php $post = affichage(102);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Lawrencium"><?php $post = affichage(103);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Rutherfordium"><?php $post = affichage(104);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Dubnium"><?php $post = affichage(105);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'".$post['presentation']."</p>"; ?></div>
<div id="Seaborgium"><?php $post = affichage(106);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Bohrium"><?php $post = affichage(107);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Hassium"><?php $post = affichage(108);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Meitnérium"><?php $post = affichage(109);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Darmstadtium"><?php $post = affichage(110);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Roentgenium"><?php $post = affichage(111);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Copernicium"><?php $post = affichage(112);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Nihonium"><?php $post = affichage(113);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Flérovium"><?php $post = affichage(114);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Moscovium"><?php $post = affichage(115);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Livermorium"><?php $post = affichage(116);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Tennessine"><?php $post = affichage(117);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>
<div id="Oganesson"><?php $post = affichage(118);echo "<h1>".$post['nom']."</h1>";echo "<p class='textPresentation'>".$post['presentation']."</p>"; ?></div>

<h1 class="titre">Tableau périodique des éléments chimiques</h1>
<h2 class="titreEtat">Visualisation des éléments par état</h2>
<h2 class="titreChoixElement">Choisissez un élément a étudier</h2>
<h2 class="titreMetauxOuNON">Légende des métaux ou non métaux</h2>