-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le :  jeu. 25 juin 2020 à 15:49
-- Version du serveur :  5.7.26
-- Version de PHP :  7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `Mendeleiev`
--

-- --------------------------------------------------------

--
-- Structure de la table `atomes`
--

CREATE TABLE `atomes` (
  `id` int(11) NOT NULL,
  `numero` int(11) NOT NULL,
  `nom` varchar(100) NOT NULL,
  `symbole` varchar(15) NOT NULL,
  `masse_atomique` varchar(11) NOT NULL,
  `presentation` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `atomes`
--

INSERT INTO `atomes` (`id`, `numero`, `nom`, `symbole`, `masse_atomique`, `presentation`) VALUES
(1, 1, 'Hydrogène', 'H', '1,00794', 'L\'hydrogène est le principal constituant du Soleil et de la plupart des étoiles (dont l\'énergie provient de la fusion thermonucléaire de cet hydrogène), et de la matière interstellaire ou intergalactique. C\'est un composant majeur des planètes géantes, sous forme métallique au cœur de Jupiter et de Saturne, et sous la forme de dihydrogène solide, liquide ou gazeux dans leurs couches plus externes et dans les autres planètes géantes. Sur Terre il est surtout présent à l\'état d\'eau liquide, solide (glace) ou gazeuse (vapeur d\'eau), mais il se trouve aussi dans les émanations de certains volcans sous forme H2 et de méthane CH4.'),
(2, 2, 'Hélium', 'He', '4,002602', 'Le mot hélium a été construit à partir du grec Helios (Ἥλιος / Hếlios, « le Soleil »), cet élément ayant été observé pour la première fois dans le spectre solaire le 18 août 1868, au cours d\'une éclipse totale de Soleil, par l\'astronome Jules Janssen.  L\'hélium est, après l\'hydrogène, l\'élément le plus abondant de l\'Univers. L\'essentiel de cet hélium a été produit lors de la nucléosynthèse primordiale mais d\'autres processus en produisent, notamment la radioactivité. '),
(3, 3, 'Lithium', 'Li', '6,9395', 'Le lithium joue un rôle important en physique nucléaire. Le lithium sert à la production de tritium par la réaction : 6Li + n → 4He + 3H. Par ailleurs, le deutérure de lithium de formule 6Li2H sert de combustible à la bombe H.  Le lithium pur est un métal mou, de couleur gris argenté, qui se ternit et s\'oxyde très rapidement au contact de l\'air et de l\'eau, prenant une teinte gris foncé virant rapidement à l\'anthracite et au noir. C\'est l\'élément solide le plus léger. Comme les autres métaux alcalins, le lithium métallique réagit facilement avec l\'air et avec l\'eau. Il est pour cette raison conservé dans de l\'huile minérale pour le préserver de l\'air.'),
(4, 4, 'Béryllium', 'Be', '9,012182', 'Le béryllium a le point de fusion le plus élevé de tous les métaux légers. Il est fragile, mais plus léger et six fois plus résistant que l’aluminium.  Sa ductilité est approximativement d\'un tiers plus grande que celle de l\'acier. Il possède une excellente conductivité thermique, est non magnétique et résiste à l\'acide nitrique concentré.  Il est fortement perméable aux rayons X, et libère des neutrons quand il est frappé par des particules alpha, comme celles émises par le radium ou le polonium.'),
(5, 5, 'Bore', 'B', '10,811', 'Les composés du bore (arabe بورق - buraq, persan burah « brillant »), sont connus depuis des milliers d\'années. Dans l\'Égypte antique, le procédé de momification dépendait du natron, un minerai contenant en impuretés des borates ainsi que d\'autres sels plus communs. Il est connu par les métallurgistes et céramistes depuis la plus haute Antiquité. Les Chinois se servaient d\'une glaise à haute teneur en borax au moins depuis − 300 et les Romains, lointains héritiers des Phéniciens, utilisaient des composés de bore pour la fabrication du verre.'),
(6, 6, 'Carbone', 'C', '12,011', 'Le nom carbone vient du latin carbo, carbōnis (« charbon »). La fabrication de carbone sous forme de charbon de bois par pyrolyse du bois sous une couche de terre était aussi connue des Romains11. Le carbone sous sa forme diamant est connu depuis l\'antiquité en Asie, il est aussi mentionné dans l\'ancien testament. Son nom vient aussi du romain adámas, adámantis (« acier dur »).'),
(7, 7, 'Azote', 'N', '14,00674', 'L\'azote a de nombreux usages industriels. Il est notamment massivement employé comme engrais en agriculture industrielle (sous forme de composés d\'ammonium), au point que c\'est aujourd\'hui son principal usage dans le monde, un usage responsable d\'une pollution généralisée de l\'environnement.'),
(8, 8, 'Oxygène', 'O', '15,9994', 'La Terre était à l\'origine dépourvue de dioxygène. Celui-ci s\'est formé grâce à la photosynthèse réalisée par les végétaux, les algues et les cyanobactéries, ces dernières étant apparues il y a peut-être 2,8 milliards d\'années. Le dioxygène O2 est toxique pour les organismes anaérobies, dont faisaient partie les premières formes de vie apparues sur Terre, mais est indispensable à la respiration des organismes aérobies, qui constituent la grande majorité des espèces vivantes actuelles. '),
(9, 9, 'Fluor', 'F', '18,9984032', 'Le fluor est le plus réactif des éléments chimiques, il est d\'ailleurs généralement lié à d\'autres élémentsa. Il possède la plus forte électronégativité, d\'une valeur de 3,98. Il est le 13e élément le plus abondant dans la croûte terrestre. Quelques plantes et certaines bactéries peuvent synthétiser des composés fluorés, mais le fluor n\'a aucun rôle métabolique chez les mammifères.'),
(10, 10, 'Néon', 'Ne', '20,1797', 'Le néon est l\'un des éléments les plus abondants de l\'univers, mais il est relativement rare sur terre, car, comme l\'hélium, une grande partie du gaz s\'est échappée dans l\'espace. On le trouve principalement dans l\'atmosphère terrestre ; seules de petites quantités sont piégées dans les roches.  Comme le krypton et le xénon, le néon est découvert en 1898 par William Ramsay et Morris William Travers par distillation fractionnée de l\'air liquide. Les applications les plus connues sont les tubes fluorescents ou les lampes néon, dans lesquels le néon est excité par des décharges électriques pour briller d\'une couleur typiquement rouge-orange.'),
(11, 11, 'Sodium	', 'Na', '22,989768', 'Le sodium est depuis longtemps reconnu dans les composés, mais il ne fut pas isolé avant 1807, lorsque Sir Humphry Davy réalisa l\'électrolyse de la soude caustique. Pendant le Moyen Âge, un composé du sodium avec le nom latin de sodanum était utilisé pour le traitement des maux de tête. Le symbole du sodium, Na, vient du nom latin d\'un composé du sodium appelé natrium, qui lui-même vient du grec νίτρον (nitron), un carbonate de sodium naturel (le natron). En allemand, comme en danois ou en néerlandais, sodium se dit natrium.'),
(12, 12, 'Magnésium', 'Mg', '24,305', 'Les atomes de magnésium existent dans la nature uniquement sous forme de combinaisons avec d\'autres éléments, où il présente invariablement l\'état d\'oxydation +2. L\'élément pur est produit artificiellement par réduction ou électrolyse. Il est hautement réactif en poudre et en copeaux mais, laissé à l\'air libre, il se revêt rapidement d\'une mince couche d\'oxyde étanche réduisant sa réactivité (passivation par oxydation). Le métal pur brûle aisément sous certaines conditions (en produisant une lumière brillante, blanche, éblouissante caractéristique). En mécanique il est utilisé principalement comme composant dans les alliages d\'aluminium-magnésium (parfois appelés magnalium). Le magnésium est moins dense que l\'aluminium et l\'alliage est apprécié pour sa légèreté et sa résistance plus grande (mécanique et chimique).'),
(13, 13, 'Aluminium', 'Al', '26,981539', 'Sa légèreté, sa résistance à la corrosion, sa mise en forme variée et sa coloration durable en font un matériau important et très utilisé dans l\'industrie et l\'artisanat, malgré la technicité de sa mise en œuvre, sous forme pure ou alliée, notamment dans l\'aéronautique, les transports et la construction. Sa nature réactive en fait également un catalyseur et un additif dans l\'industrie chimique ; il est ainsi utilisé pour accroître la puissance explosive du nitrate d\'ammonium.'),
(14, 14, 'Silicium', 'Si', '28,0855', 'Sous sa forme amorphe, la silice (SiO2) provenant généralement de la terre de diatomées, est utilisée depuis très longtemps comme composant essentiel du verre. Il a depuis le milieu du xx siècle de nouveaux usages en électronique (transistor), pour la production de matériaux tels que les silicones ou, pour fabriquer des panneaux solaires photovoltaïques et en tant que biominéral, la silice amorphe est actuellement étudiée pour ses utilités en nanotechnologie.'),
(15, 15, 'Phosphore', 'P', '30,973762', 'Le nom dérive du mot grec φώσφορος (phosphoros), qui signifie « porteur de lumière » et évoque la planète Vénus, l\'étoile du berger. Cette origine a été attribuée au fait que le phosphore blanc émet de la lumière visible dans l\'obscurité quand il est exposé à l\'air, par chimiluminescence.  En raison du fait qu\'il est indispensable à la vie et d\'une consommation mondiale qui pourrait dépasser les ressources disponibles avant une centaine d\'années, l\'ONU et divers scientifiques le classent comme matière première minérale critique, qu\'il faudrait apprendre à économiser et mieux recycler.'),
(16, 16, 'Soufre', 'S', '32,066', 'C\'est un élément essentiel pour tous les êtres vivants. Le soufre sert à 90 % à préparer l\'acide sulfurique, produit de base de l\'industrie chimique. Il est notamment employé comme engrais (sulfates) (60 % de la production) et phytosanitaire fongicide (contre l\'oïdium de la vigne). Environ 34 % sert à des applications non agricoles comme la fabrication du caprolactame-monomère qui intervient dans la préparation du Nylon-6, dans les processus de lixiviation en exploitation minière, à l\'élaboration du dioxyde de titane, des tripolyphosphates pour les détergents, à l\'alimentation animale et humaine, à la fabrication de la pâte à papier Il est aussi utilisé pour fabriquer la poudre à canon, les laxatifs, était utilisé dans les allumettes, des insecticides, etc.'),
(17, 17, 'Chlore	', 'Cl', '35,4527', 'Le chlore est abondant dans la nature, son dérivé le plus important est le sel de table ou chlorure de sodium (NaCl). Ce dernier est nécessaire à de nombreuses formes de vie.  Le chlore, à l\'état de corps simple, se présente sous la forme de la molécule de dichlore Cl2, qui est un gaz jaune-vert 2,5 fois plus dense que l\'air, aux conditions normales de température et de pression. Ce gaz a une odeur suffocante très désagréable et est extrêmement toxique.'),
(18, 18, 'Argon', 'Ar', '39,948', 'Le nom argon provient du grec ancien ἀργόν, signifiant « oisif », « paresseux », en référence au fait que cet élément est chimiquement inerte.L\'argon est produit industriellement par distillation fractionnée d\'air liquiéfié. Il est utilisé essentiellement comme atmosphère inerte pour le soudage et divers procédés industriels à haute température faisant intervenir des substances réactives. On utilise ainsi une atmosphère d\'argon dans les fours à arc électrique au graphite pour éviter la combustion de ce dernier. On emploie également l\'argon dans l\'éclairage par lampes à incandescence, tubes fluorescents et tubes à gaz. Il permet de réaliser des lasers à gaz bleu-vert.'),
(19, 19, 'Potassium', 'K', '39,0983', 'Le potassium est un solide mou que l\'on peut couper facilement à l’aide d’un couteau. Les surfaces fraîchement tranchées ont un aspect métallique. Il s’oxyde rapidement à l’air et doit donc être conservé dans l’huile.  Comme les autres métaux alcalins, l’eau se décompose à son contact avec formation de dihydrogène. Lorsqu’il est plongé dans l’eau, il réagit violemment8 en produisant du dihydrogène qui peut s’enflammer, voire détoner, en présence d’oxygène et d’une source de chaleur.  Ses sels émettent une couleur violette lorsqu’ils sont exposés à une flamme.'),
(20, 20, 'Calcium', 'Ca', '40,078', 'La chaux était déjà préparée par les Romains dès le ier siècle, mais ce n\'est qu\'en 1808 que le calcium fut découvert. En apprenant que Jöns Jacob Berzelius et Magnus Martin Pontin (de) avaient préparé un amalgame de calcium par électrolyse de la chaux dans du mercure, Humphry Davy fut capable d\'isoler le métal impur.'),
(21, 21, 'Scandium', 'Sc', '44,95591', 'Le scandium est un élément métallique mou, rare, trivalent, très léger qui devient jaunâtre ou rose lorsqu\'il est exposé à l\'air. Cet élément a des propriétés chimiques intermédiaires entre celles de l\'aluminium et de l\'yttrium. L\'état d\'oxydation le plus commun du scandium est +3.'),
(22, 22, 'Titane', 'Ti', '47,88', 'Le corps pur titane est un métal léger, résistant, d\'aspect blanc métallique, qui résiste à la corrosion. Il est principalement utilisé dans les alliages légers et résistants, et son oxyde est utilisé comme pigment blanc. Les propriétés industriellement intéressantes du titane sont sa résistance à la corrosion, souvent associée à la résistance à l’érosion et au feu, la biocompatibilité, mais aussi ses propriétés mécaniques (résistance, ductilité, fatigue, etc.) qui permettent notamment de façonner des pièces fines et légères comme les articles de sport, mais aussi des prothèses orthopédiques.'),
(23, 23, 'Vanadium', 'V', '50,9415', 'Le vanadium est un métal blanc, brillant, dur et ductile. Il possède une bonne résistance à la corrosion par les composés alcalins, ainsi qu\'aux acides chlorhydrique et sulfurique. Il s\'oxyde rapidement à environ 660 °C. Le vanadium possède une bonne force structurelle ainsi qu\'une faible section efficace d\'interaction avec les neutrons de fission, ce qui le rend utile dans les applications nucléaires. C\'est un métal qui présente à la fois des caractéristiques acide et basique.'),
(24, 24, 'Chrome', 'Cr', '51,9961', 'Ces éléments se caractérisent par des corps simples métalliques qui ont des points de fusion élevés, des pressions de vapeur parmi les plus basses, des faibles coefficients de dilatation thermique. Sur la surface de ces trois métaux, il se forme à température ambiante une couche d\'oxyde(s) entravant souvent les réactions chimiques destructrices. La stabilité face aux bases et oxydants faibles est ainsi assurée. Toutefois les milieux alcalins fondus transforment ces métaux en ions chromates, molybdates et tungstanates.'),
(25, 25, 'Manganèse', 'Mn', '54,93805', 'On a trouvé du manganèse dans les minerais de fer utilisés par d\'anciens peuples grecs, notamment les Lacédémoniens ou Spartiates. Il semble plausible que l\'exceptionnelle dureté de l\'acier spartiate proviennent de la production régulée d\'un alliage fer-manganèse. Les hommes de l\'art, depuis l\'Antiquité, sans connaissance chimique moderne des corps minéraux, savent utiliser la magnésie noire ou oxyde de manganèse naturel en tant que \"fondant actif\". Minerais de fer et oxydes de manganèse donnent par réduction au charbon de bois divers composés ferromanganèses, employables pour fabriquer des lames de fer à couche d\'acier ou des bronzes spécifiques après coulée avec le cuivre.'),
(26, 26, 'Fer', 'Fe', '55,847', 'Le corps simple est le métal et le matériau ferromagnétique le plus courant dans la vie quotidienne, le plus souvent sous forme d\'alliages divers. Le fer pur est un métal de transition ductile, mais l\'adjonction de très faibles quantités d\'éléments d\'additions modifie considérablement ses propriétés mécaniques. Allié au carbone et avec d\'autres éléments d\'additions il forme les aciers, dont la sensibilité aux traitements thermomécaniques permet de diversifier encore plus les propriétés du matériau.'),
(27, 27, 'Cobalt	', 'Co', '58,9332', 'Le corps simple cobalt a des propriétés physiques assez voisines de celles du fer et du nickel. D\'un point de vue chimique, il est moins réactif que le fer. Le cobalt est aussi un élément du groupe 9, dont les trois premiers Co, Rh et Ir constituent le groupe du cobalt.Des minéraux naturels de cobalt, sous forme de peintures, émaux ou vernis, sont utilisés depuis la plus haute Antiquité, en particulier vers 2600 av. J.-C. en Égypte ou dans les civilisations de Mésopotamie ayant donné naissance à Babylone. Ainsi l\'archéologue retrouve des décors bleus sur des poteries ou vaisselles de terre cuite. Des perles de verre teinté au bleu de cobalt sont communes vers 2200 av. J.-C. dans l\'actuel Iran.'),
(28, 28, 'Nickel', 'Ni', '58,69', 'Le nickel est fréquemment associé au cobalt dans les dépôts miniers, il est particulièrement apprécié pour les alliages qu\'il forme. Longtemps confondu avec l\'argent ou le cuivre, le nickel est aujourd\'hui utilisé pour la confection de monnaie et en alliage dans l\'industrie.'),
(29, 29, 'Cuivre', 'Cu', '63,546', 'Naturellement présent dans la croûte terrestre, le cuivre à faible dose est essentiel au développement de toute forme de vie. Il est majoritairement utilisé par l\'homme sous forme de métal. Le cuivre pur est un des seuls métaux colorés avec l\'or et l\'osmium9. Il présente sur ses surfaces fraîches une teinte ou un éclat métallique rose saumon : ce « métal rouge » apprécié en orfèvrerie et en bijouterie, par exemple comme support de pièces émaillés ou émaux rares, était dédié à la déesse de la beauté Aphrodite et aux artistes.'),
(30, 30, 'Zinc', 'Zn', '65,39', 'Le métal zinc est utilisé comme anode dans les premières piles à empilement métallique, par exemple les piles voltaïques au début du xixe siècle. Les premiers alliages de zinc, plomb et étain sous pression sont mis au point entre 1804 et 1814 : ils permettent d\'obtenir des caractères d\'imprimerie plus résistants.  Le chimiste britannique Edward Frankland découvre les premiers composés organométalliques à base de zinc (à liaison C - Zn) vers 1850, en appliquant et maîtrisant des techniques de chauffage à reflux et de distillation sous vide ou atmosphère inerte.'),
(31, 31, 'Gallium', 'Ga', '69,723', 'Le gallium pur a un aspect argenté et il se brise sous forme solide de la même manière que le verre. Le volume du gallium augmente de 3,1 % lorsqu\'il se solidifiea et pour cette raison ne doit pas être stocké dans un récipient en verre ou en métal. Le gallium corrode la plupart des autres métaux en diffusant dans le réseau métallique.'),
(32, 32, 'Germanium', 'Ge', '72,61', 'Ce métalloïde est semi-conducteur et cristallise avec la même structure que le diamant, tout comme le silicium. Il possède cinq isotopes naturels, dont le Ge, qui est faiblement radioactif. Au moins 27 radioisotopes ont été synthétisés.  La quasi-totalité du germanium est récupérée dans les fonderies de zinc (sous-produit de fusion).'),
(33, 33, 'Arsenic', 'As', '74,92159', 'L\'arsenic corps simple polymorphe existe à l\'état natif au moins sous deux variétés allotropiques, qui sont autant d\'espèces minérales définies de la catégorie élément natif, soient l\'arsenic natif et l\'arsénolamprite. De grandes masses d\'arsenic natif, accumulées lentement par l\'effet des eaux acides d\'infiltrations minières, ont été trouvées dans les anciennes mines de Sainte-Marie-aux-Mines.'),
(34, 34, 'Sélénium', 'Se', '78,96', 'Le sélénium se concentre dans certaines plantes, céréales ou herbes, ou levures. Les concentrations peuvent être parfois trop élevées et toxiques, mais le plus souvent les très faibles concentrations des céréales ne sont pas toujours assimilables par la présence conjointes de bio-complexants, ce qui entraîne des déficiences drastiques nuisibles au bien-être et à la santé, dans certaines régions du globe.'),
(35, 35, 'Brome', 'Br', '79,904', 'Outre qu\'il peut contribuer à dégrader la couche d\'ozone, il semble jouer un rôle de catalyseur dans le phénomène atmosphérique écotoxicologiquement préoccupant dit de « pluies de mercure » (impliqué dans environ 80 % des cas). Il est notamment émis dans l\'air par l\'incinération des déchets et pour de nombreux secteurs, il n\'y a pas de valeurs limites d\'émission (VLE) dans l\'air ou dans les rejets d\'eaux usées.'),
(36, 36, 'Krypton', 'Kr', '83,8', 'Du fait de son prix élevé, le krypton est assez peu utilisé. L\'utilisation de l\'argon lui est souvent préférée, en particulier pour certaines soudures, car l\'argon est un gaz inerte nettement moins cher.Applications électriques : les lampes au krypton produisent une lumière de haute intensité avec une longue durée de vie.Double vitrage, le krypton est utilisé avec l’argon en remplissage pour augmenter l\'isolation thermique ainsi que dans le domaine médicale.'),
(37, 37, 'Rubidium	', 'Rb', '85,4678', 'Son nom vient du latin rubidus (rouge foncé), du fait de la couleur rouge des raies spectrales qui ont permis à Robert Wilhelm Bunsen et Gustav Kirchhoff de le détecter en 1861 dans la lépidolite. Il a été isolé l\'année suivante par Bunsen.  Comme les autres métaux alcalins, il s\'enflamme spontanément au contact avec l\'air et réagit violemment avec l\'eau.  Sous forme de condensat de Bose-Einstein, il a la propriété de réduire la vitesse de la lumière qui la traverse à moins de 60 km/h.'),
(38, 38, 'Strontium', 'Sr', '87,62', 'Le strontium, comme le calcium, est un alcalino-terreux. Il est mou, malléable, gris-jaune. Au contact avec l\'air, il forme un film d\'oxyde protecteur (passivation). Il s\'enflamme et brûle facilement dans l\'air et réagit avec l\'eau.'),
(39, 39, 'Yttrium', 'Y', '88,90585', ' L\'yttrium est un élément de transition d\'apparence métallique, qui possède un comportement chimique proche de celui des lanthanides, et classé historiquement parmi les terres rares, avec le scandium et les lanthanides. Dans la nature, il ne se rencontre jamais à l\'état natif, mais le plus souvent combiné avec des lanthanides dans des minerais de terres-rares. '),
(40, 40, 'Zirconium	', 'Zr', '91,224', 'Son principal minerai, le zircon ZrSiO4 se présente quelquefois sous forme d\'une pierre précieuse, l\'hyacinthe. Il est généralement associé au titane et à l\'hafnium. La teneur massique en hafnium est à peu près constante et égale à 2 %. Le zircon est un constituant des granites, il se concentre dans les sables issus de la décomposition du granite.'),
(41, 41, 'Niobium	', 'Nb', '92,90638', 'Par son point de fusion et sa densité modérée, le métal Nb se rapproche du molybdène. Le niobium appartient au groupe des cinq métaux réfractaires au sens où leur point de fusion est supérieur à celui du platine. Les quatre autres corps simples sont le tantale Ta, le tungstène W, le molybdène Mo et le rhénium Re.Le niobium et le tantale se trouvent souvent ensemble dans la nature. Les deux corps simples sont difficiles à isoler et à séparer à l\'état pur.'),
(42, 42, 'Molybdène', 'Mo', '95,94', 'Le molybdène est un métal de transition. Le métal pur est d\'aspect blanc métallique et il est très dur. Il a été souvent confondu avec du minerai de graphite et de galène. Il a un haut module d\'élasticité et seuls le tungstène et le tantale, des métaux plus aisément disponibles, ont des points de fusion plus élevés.'),
(43, 43, 'Technétium', 'Tc', '98,9063', 'Le technétium est l\'élément le plus léger ne possédant pas d\'isotope stable. Les propriétés chimiques de ce métal de transition radioactif de couleur gris métallique, rarement présent dans la nature, sont intermédiaires entre celles du rhénium et du manganèse. Son nom provient du grec τεχνητός, tekhnêtos, qui signifie « artificiel » : il a été le premier élément chimique produit artificiellement. Le technétium est aussi le plus léger des éléments découverts par création artificielle.'),
(44, 44, 'Ruthénium', 'Ru', '101,07', 'Il s\'agit d\'un métal relativement dur, mais cassant. Il fond vers 2 330 °C et bout vers 4 100 °C. Il a des propriétés analogues à l\'osmium et au platine. Elle se décline en deux versants, via une métallurgie des poudres ou des techniques de fusion à l\'arc électrique sous atmosphère inerte d\'argon.  Le ruthénium présente une grande résistance à froid et à chaud, placés aux milieux chimiquement agressifs, aux acides et aux bases.  Le ruthénium est inaltérable à l\'air et insoluble dans l\'eau, il est pratiquement inattaquable par les acides, y compris par l\'eau régale, à moins d\'ajouter du chlorate de potassium, opération qui rend l\'oxydation explosive9.'),
(45, 45, 'Rhodium', 'Rh', '102,9055', 'Le rhodium natif, très rare, est le minéral qui correspond au corps simple métallique, alors que la rhodite est un alliage d’or et de rhodium.  Le rhodium est un métal rare et cher, la production mondiale provenant principalement de la récupération au cours de traitement d’autres minerais. Elle n’était que de 12 tonnes par an dans les années 1990 et de 20 tonnes par an en 2010. L’Afrique du Sud, l’Oural (Russie) et l’Ontario (Canada) fournissent l’essentiel de la production mondiale de rhodium'),
(46, 46, 'Palladium', 'Pd', '106,42', 'Le palladium est un métal blanc argenté ou de couleur acier brillant, parfois gris blanc, malléable et mou, assez semblable au platine. Malléable et très ductile, il peut être travaillé à la forge de façon à relever par écrouissage sa dureté, il est laminable à froid à l\'instar de l\'or en feuilles très minces de l\'ordre du dix millième de millimètre.'),
(47, 47, 'Argent', 'Ag', '107,8682', 'L\'argent est présent dans le sous-sol à l\'état natif, c\'est l\'argent natif du Mexique, du Pérou, du Chili, de Saxe, du lac Supérieur ou de Norvège, il est assez rare en cristaux isolés, mais fréquent en fils contournés et minces placages, à surface généralement altérée de teinte sombre ou très souvent dispersés en une multitude de structures réticulaire ou filaires. Il forme des amas parfois sous la forme de veines et filons à gangues siliceuse ou carbonatée, plus rarement dispersé en pépites compactes.'),
(48, 48, 'Cadmium', 'Cd', '112,411', 'Le cadmium est un élément toxique (notamment responsable de la maladie Itai-itai) et écotoxique, parmi les plus problématiques sur le plan de la santé environnementale parmi les éléments traces métalliques et métaux lourds.'),
(49, 49, 'Indium	', 'In', '114,82', 'Le corps simple indium In est un métal gris brillant, à bas point de fusion à peine supérieur à 156 °C, résistant à la corrosion atmosphérique.Il est rare. L\'indium est resté un « métal ou un élément de laboratoire » jusque dans le début de l\'entre-deux-guerres. En 1924, on découvre que l\'indium peut stabiliser les métaux non ferreux11. En 1940, l\'indium comme revêtement protecteur et anticorrosion de longue durée améliore les roulements à billes du matériel aéronautique militaire.'),
(50, 50, 'Étain', 'Sn', '118,71', 'L\'étain est connu depuis l\'antiquité où il servait à protéger la vaisselle de l\'oxydation et pour préparer le bronze. Il est toujours utilisé pour cet usage, et pour le brasage. Cet élément est peu toxique. Rare à l\'état natif, l\'étain est essentiellement extrait d\'un minéral appelé cassitérite où il se trouve sous forme d\'oxyde SnO2.'),
(51, 51, 'Antimoine	', 'Sb', '121,75', 'Le corps simple antimoine est un métalloïde polymorphe, toxique et cancérigène, tout comme l\'arsenic (auquel il est souvent associé, par exemple dans les munitions à base de plomb).  L\'adjectif antimonié qualifie un corps ou une matière qui contient de l\'antimoine.'),
(52, 52, 'Tellure', 'Te', '127,6', 'Le tellurium a été découvert moins de deux décennies avant le sélénium, dont le nom fait référence à la Lune. Le Suédois Berzelius, spécialiste des occurrences et des impuretés du tellurium, a prouvé l\'existence du corps simple et de l\'élément sélénium dans les chambres de plomb du procédé menant à l\'acide sulfurique.'),
(53, 53, 'Iode', 'I	', '126,90447', 'L\'iode est un composant des hormones thyroïdiennes, synthétisées par la glande thyroïde. Les radioisotopes de l\'iode sont par conséquent susceptibles de provoquer un cancer de la thyroïde lorsqu\'ils sont absorbés par l\'organisme. L\'iode 131, en raison de sa radioactivité β, est à ce titre l\'un des produits de fission nucléaire les plus cancérogènes qui soient.'),
(54, 54, 'Xénon', 'Xe', '131,29', 'On extrait le xénon par distillation de l\'air. Pour distiller de l\'air, il faut le rendre liquide en le compressant (il s\'échauffe en restant gazeux, mais en le maintenant compressé et en le refroidissant, il se liquéfie). On peut alors extraire le xénon par distillation fractionnée de l\'air devenu liquide.'),
(55, 55, 'Césium', 'Cs', '132,90543', 'Le césium est le plus alcalin des métaux alcalins (base la plus forte connue ; assez pour attaquer le verre). Ses propriétés chimiques sont proches de celles du rubidium et du potassium, qui appartiennent à la même famille. Il réagit violemment avec l\'eau et l\'air (réaction explosive). Il est extrêmement réactif et pyrophorique, et réagit avec l\'eau même à une température aussi basse que -116 °C.'),
(56, 56, 'Baryum', 'Ba', '137,327', 'C\'est un métal alcalino-terreux mou argenté qui fond à 850 °C. Il est utilisé pur pour le piégeage des gaz résiduels dans les tubes cathodiques ou comme révélateur de présence d\'air dans les capteurs solaires thermiques à tube sous vide. Fabrication du papier photographique, de lubrifiant résistant à haute température...'),
(57, 57, 'Lanthane', 'La	', '138,9055', 'Le lanthane a donné son nom à la famille des lanthanides qui font partie des terres rares. Son nom dérive du mot grec « lanthanein », ce qui signifie « cacher » : le lanthane est resté longtemps caché dans l\'oxyde de cérium.  À température ambiante le lanthane est un métal gris argent, malléable, ductile, assez mou pour être coupé au couteau. Il s\'oxyde à l\'air et dans l\'eau.'),
(58, 58, 'Cérium', 'Ce', '140,115', 'Le cérium est un métal gris , le plus abondant du groupe des terres rares.  À température ambiante, il est malléable et s\'oxyde rapidement à l\'air. le cérium entre dans la composition du mischmétal, base des pierres à briquet. le dioxyde de cérium (CeO2) est l\'une des meilleures poudres de polissage du verre.'),
(59, 59, 'Praséodyme	', 'Pr', '140,90765', 'Le praséodyme est un métal doux, argenté, malléable et ductile du groupe des lanthanides. Il est un peu plus résistant à la corrosion dans l\'air que l\'europium, le lanthane, le cérium et le néodyme mais il produit une couche verte d\'oxyde peu adhérente qui éclate lorsqu\'elle est exposée à l\'air. Le métal est ainsi exposé de nouveau à l\'oxydation. On conserve donc, en général, le praséodyme, sous huile ou en ampoules scellées.'),
(60, 60, 'Néodyme', 'Nd', '144,24', 'Le néodyme est un élément chimique, de symbole Nd et de numéro atomique 60. C\'est un métal gris argent du groupe des terres rares.Le néodyme a été utilisé avec d\'autres sels de terres rares et comme le thorium dans des produits pharmaceutiques à usage gynécologique comme les « ovules néothorium Millot » dans les années 1920-1930...'),
(61, 61, 'Prométhium', 'Pm', '146,9151', 'L\'élément ne possède pas d\'autre application courante que les composés luminescents du fait de sa radioactivité. Il a également été utilisé comme source de chaleur dans le cadre du Systems Nuclear Auxiliary Powers et dans des stimulateurs cardiaques. Son usage en tant que source potentielle de rayons X portable est présentement à l\'étude'),
(62, 62, 'Samarium', 'Sm', '150,36', 'Le samarium est un métal rare sur la Terre. Il est de couleur argentée, relativement stable à l\'air libre et s\'enflamme spontanément à 150 °C. Trois modifications de la structure du métal existent notamment à 734 °C et 922 °C. Les aimants en SmCo5 possèdent la résistance de démagnétisation la plus élevée connue.'),
(63, 63, 'Europium	', 'Eu', '151,965', 'Comme tous les isotopes des lanthanides pauvres en neutron, l\'europium a une bonne capacité à absorber les neutrons. On a aussi étudié son utilisation dans les réacteurs nucléaires. Majoritairement les barres de contrôle des réacteurs nucléaires des sous-marins russes utilisent l\'europium. La section efficace est de 2 980 barns et les deux isotopes stables sont capturants.'),
(64, 64, 'Gadolinium', 'Gd', '157,25', 'Le gadolinium est un métal faisant partie des terres rares. Il est gris argent, malléable et ductile à la température ambiante. On ajoute du gadolinium (jusqu\'à concurrence de 1 %) à de l\'acier au chrome pour améliorer la dureté et les propriétés de transformation. Des développements sont en cours pour mettre au point des lasers à rayons X.'),
(65, 65, 'Terbium', 'Tb', '158,92534', 'Le terbium est un métal d\'aspect gris argenté. Comme les autres membres de la famille des lanthanides, il est malléable, ductile et assez mou pour être coupé avec un couteau. Il est assez stable dans l\'air, et existe sous deux formes allotropiques, avec un changement de phase à 1 289 °C.'),
(66, 66, 'Dysprosium', 'Dy', '162,5', 'Le dysprosium est un métal faisant partie des terres rares, d\'aspect gris argenté. Comme les autres membres de la famille des lanthanides, il est malléable, ductile et assez mou pour être coupé avec un couteau. Il est assez stable dans l\'air. On ajoute du dysprosium à des alliages de magnésium que l\'on utilise dans l\'aéronautique. Il augmente la dureté du matériau et facilite sa transformation.'),
(67, 67, 'Holmium', 'Ho', '164,93032', 'L\'holmium est un métal du groupe des terres rares. Comme les autres lanthanides, il est malléable et ductile à température ambiante, s\'oxyde lentement dans l\'air sec mais rapidement dans l\'air humide. Les lasers YAG (grenat yttrium-aluminium), dopés avec des composés d\'holmium, fournissent une lumière infrarouge (à 2,1 µm) et sont principalement utilisés à des fins médicales.'),
(68, 68, 'Erbium', 'Er', '167,26', 'L\'erbium est l\'une des terres rares les plus abondantes. Sa concentration dans l\'écorce terrestre est d\'environ 3,5 g/tonne, ce qui est presque le double de celle de l\'étain et en fait le 44e élément par ordre d\'abondance. Coloré en rose, il permet, entre autres, de rehausser la qualité des photos prises en ambiance nuageuse.'),
(69, 69, 'Thulium', 'Tm', '168,93421', 'Le thulium pur est brillant et argenté. Il ternit lorsqu\'il est exposé à l\'air. Il peut être coupé au couteau et il est malléable et ductile. Le sulfure de zinc dopé avec de l\'oxyde de thulium (Tm2O3) sert comme substance phosphorescente bleue pour les tubes cathodiques.'),
(70, 70, 'Lutécium', 'Lu', '174,967', 'L\'ytterbium est un métal du groupe des terres rares. Comme les autres lanthanides, il est gris argent, malléable et ductile à la température ambiante. Il doit être conservé à l\'abri de l\'air, surtout humide. Très peu d\'utilisations courantes, amélioration des propriétés de traitement de l\'acier inoxydable et ion actif de plus en plus utilisé dans des cristaux laser comme Yb:YAG ou Yb:KYW émettant à environ 1030-1070 nm (environ 1 micromètre) dans le proche infrarouge.'),
(71, 71, 'Lutécium', 'Lu', '174,967', 'Le lutécium est un métal gris argenté, mou et ductile. Ses applications sont limitées en raison de sa rareté et de son prix élevé. La production de cet élément demande en effet de le séparer des autres terres rares avec lesquelles il est toujours présent.'),
(72, 72, 'Hafnium', 'Hf', '178,49', 'C\'est un métal ductile, brillant et argenté. Il résiste à la corrosion et est chimiquement semblable au zirconium. Les propriétés du hafnium sont affectées par la présence d\'impuretés de zirconium et ces deux éléments sont parmi les plus difficiles à séparer. La seule différence notable entre eux est la densité. Comme pour le zirconium, le hafnium est extrait du minerai comme métal pur en réduisant le tétra-halogénure par le magnésium, la réaction est faite sous atmosphère d\'argon car les deux métaux pourraient se combiner avec d\'autres gaz.'),
(73, 73, 'Tantale', 'Ta', '180,9479', 'Le corps simple tantale est un métal de transition gris-bleu, lourd, dur mais ductile, très résistant à la corrosion des acides, et bon conducteur de la chaleur et de l\'électricité. L’électronique est la première application du tantale. En effet, environ 68 % de la production annuelle est utilisée juste pour ce domaine. Il est principalement utilisé dans la construction de condensateurs.'),
(74, 74, 'Tungstène', 'W	', '183,85', 'Le corps simple tungstène est un métal de transition gris-acier blanc, très dur et lourd. Sous sa forme pure, il est principalement utilisé dans des applications électriques (filaments de lampe à incandescence), mais sous forme de composés ou d\'alliages, il possède de nombreuses applications, comme la réalisation d\'outils nécessitant une grande dureté (forets, poudres abrasives, etc.).'),
(75, 75, 'Rhénium', 'Re', '186,207', 'Le rhénium a peu d\'applications, en raison de sa rareté et des coûts de production élevés. On se sert du rhénium pour améliorer la résistance thermique du filament des fours électriques, dans la production de thermocouples et comme catalyseur dans l\'industrie chimique.'),
(76, 76, 'Osmium', 'Os', '190,2', 'C\'est un métal de transition appartenant au groupe du platine. Il est l\'élément naturel le plus dense sur Terre. Il est le plus souvent trouvé nativement en alliage avec le platine ou l\'iridium. Les alliages d\'osmium sont employés notamment dans les pointes de stylo-plume, les contacts électriques et dans d\'autres applications où sa dureté et sa résistance extrêmes sont requises.'),
(77, 77, 'Iridium	', 'Ir', '192,22', 'Il figure en quantité non négligeable dans les gisements secondaires d\'or natif et de platine natif.Le corps simple est un métal lourd qualifié de platinoïde pour son analogie avec le platine. Il est dur, dense, cassant et d\'aspect blanc argenté ou blanc grisâtre à lustre métallique. Il est très résistant à la corrosion. La réflectance lumineuse de ce métal pur n\'est dépassée que par celle de l\'argent.'),
(78, 78, 'Platine', 'Pt', '195,08', 'Ce corps simple est un métal de transition de couleur blanche à gris-blanche, à reflet métallique, brillante. Ce platinoïde lourd a une densité élevée avoisinant 21,4 ; il est assez mou et malléable, très ductile (il peut être tréfilé en fil très fin), rare et précieux et très résistant à la corrosion.  Il s\'agit d\'un métal noble (avec l\'argent et l\'or), d\'un métal précieux non magnétique (pur), bon conducteur de la chaleur et de l\'électricité. Son coefficient de dilatation thermique est proche de celui du verre.'),
(79, 79, 'Or	', 'Au', '196,96654', 'L\'or pur est un métal noble, malléable et très ductile, le plus ductile des métaux connus, et à la fois dense et tendre. Ce cristal à réseau cubique à faces centrées est un métal jaune plus ou moins brillant, qui acquiert un grand éclat après polissage. Il est relativement chimiquement inerte, très stable car il ne s\'oxyde ni à l\'air ni dans l\'eau dans les conditions normales de température et de pression : le fait qu\'il préserve son éclat, perçu comme esthétique par toutes les cultures humaines, lui confère l\'essentiel de sa valeur. Il peut néanmoins former de l\'oxyde d\'or sous haute pression ou en milieu réactif.'),
(80, 80, 'Mercure', 'Hg', '200,59', 'Le corps simple mercure est un métal, liquide et peu visqueux dans les conditions normales de température et de pression. On l\'a appelé vif-argent jusqu\'au début du xixe siècle.On trouve le mercure sous forme d\'un corps simple comme le mercure natif, d\'ions et de composés à l\'état oxydé, plus fréquemment sous forme de sulfures, tels que le sulfure de mercure (HgS) de couleur rouge vermillon, nommé cinabre en minéralogie, et plus rarement sous forme d\'oxydes ou de chlorures. Le cinabre est son principal minerai.'),
(81, 81, 'Thallium', 'Tl', '204,3833', 'C\'est un métal gris, malléable, très tendre (se coupe au couteau) qui ressemble au plomb et se ternit comme lui lorsqu\'il est exposé à l\'air.  Il est présent dans les nodules sous-marins de manganèse. De nombreuses utilisations dont le thermomètres, formant avec le mercure, un eutectique restant liquide jusqu\'à −60 °C.'),
(82, 82, 'Plomb', 'Pb', '207,2', 'Le plomb - relativement abondant dans la croûte terrestre - est l\'un des métaux les plus anciennement connus et travaillés. On en a trouvé dans des pigments recouvrant des tombes ou dépouilles préhistoriques (40 000 ans av. J.-C.), mais aussi des objets.'),
(83, 83, 'Bismuth', 'Bi', '208,98037', 'Le corps simple bismuth est un métal pauvre blanc d\'argent, à reflet rougeâtre brillant, dur et cassant, dont tous les sels et les vapeurs sont toxiques. Étant peu soluble il y est supposé peu mobile, mais certaines formes du bismuth sont volatiles. Son cycle biogéoéchimique est très mal connu. Comme ce n\'est pas un métal recherché dans les analyses environnementales de routines pour l\'eau, le sol, l\'air, ou les aliments, sa cinétique environnementale reste mal connue.'),
(84, 84, 'Polonium', 'Po', '208,9824', 'Le polonium est un métal pauvre de faible point de fusion (254 °C). Il est aussi très volatil et finirait par se sublimer entièrement même à température ambiante. Il perd 50 % de sa masse en 45 heures en n\'étant chauffé qu\'à 55 °C, peut-être par désagrégation à l\'échelle atomique induite par sa très forte activité α, laquelle a d\'ailleurs pour effet de le maintenir à température élevée.'),
(85, 85, 'Astate', 'At', '209,9871', 'L\'astate est un élément extrêmement radioactif ; tous ses isotopes connus ont des demi-vies de 8,1 heures ou moins et se désintégrent en autres isotopes de l\'astate, en bismuth, en polonium ou en radon. La plupart de ses isotopes sont très instables, avec des demi-vies de moins d\'une seconde.'),
(86, 86, 'Radon', 'Rn', '222,0176', 'Le radon n\'existe pas sous forme de corps stable et tous ses isotopes connus sont radioactifs. Son isotope le plus stable est le 222Rn, qui a une demi-vie de 3,8 jours et qui a été utilisé en radiothérapie jusque dans les années 1950. Son intense radioactivité a entravé son étude chimique approfondie, et seuls quelques-uns de ses composés sont bien connus.'),
(87, 87, 'Francium', 'Fr', '223,0197', 'C\'est le second élément le plus rare parmi les 92 premiers éléments de la classification périodique, après l’astate : il n\'en existerait qu\'une trentaine de grammes dans la croûte terrestre. Cette rareté est due à son existence transitoire, en tant que produit de désintégration de l\'actinium. '),
(88, 88, 'Radium', 'Ra', '226,0254', 'Le radium a été découvert par Marie Skłodowska-Curie et son mari Pierre Curie le 21 décembre 1898, dans un minerai d\'uraninite. Lors de l\'étude de ce minéral, les Curie en avaient extrait tout l\'uranium, pour constater que le reliquat était encore fortement radioactif.'),
(89, 89, 'Actinium', 'Ac', '227,0278', 'Le corps simple actinium est un métal blanc argenté et mou. On l’extrait en petites quantités des minerais d’uranium (c’est un produit de la chaîne de désintégration de 235U) ou par réaction nucléaire. L\'actinium est un métal, radioactif mou de couleur blanc-argenté. Son module de cisaillement est similaire à celui du plomb. Du fait de sa forte radioactivité, l’actinium brille dans le noir d’une lueur bleue pâle, venant de l’air environnant ionisé par les particules énergétiques qu’il émet.'),
(90, 90, 'Thorium', 'Th', '232,0381', 'Ce nouveau métal resta pratiquement inutilisé jusqu\'à l\'invention du manchon à incandescence en 1885. Le thorium sera beaucoup utilisé dans ces lampes jusqu’à ce que le marché s’effondre à la fin de la Première Guerre mondiale. La radioactivité du thorium a été découverte en 1898 indépendamment par la physicienne Marie Curie et le chimiste Gerhard Carl Schmidt.'),
(91, 91, 'Protactinium	', 'Pa', '231,0359', 'Le protactinium est présent en très faible quantité (typiquement de l\'ordre de 1 ppm) dans les gisements naturels de minéraux uranifères (type pechblende), où il se forme lors de la lente décroissance radioactive de l\'uranium. C\'est un des plus rares et des plus coûteux des éléments naturels.'),
(92, 92, 'Uranium', 'U', '238,0289', 'C\'est un métal lourd radioactif. Sa radioactivité, additionnée à celle de ses descendants dans sa chaîne de désintégration, développe une puissance de 0,082 watt par tonne d\'uranium, ce qui en fait, avec le thorium 232 (quatre fois plus abondant, mais trois fois moins radioactif) et le potassium 40, la principale source de chaleur qui tend à maintenir les hautes températures du manteau terrestre, en ralentissant de beaucoup son refroidissement.'),
(93, 93, 'Neptunium', 'Np', '237,0482', 'Élément métallique radioactif, le neptunium est le premier des transuraniens et appartient à la famille des actinides. Il fut découvert en 1940 à l\'Université de Californie. Comme il vient après l\'uranium dans le tableau périodique, il fut baptisé en référence à la planète Neptune, qui vient après Uranus dans le système solaire.'),
(94, 94, 'Plutonium	', 'Pu', '244,0642', 'Le plutonium a été produit et isolé pour la première fois le 14 décembre 1940 à l\'université de Californie à Berkeley en bombardant de l\'uranium 238 par du deutérium. Venant à la suite de l\'uranium et du neptunium dans le tableau périodique, ce nouvel élément chimique a été nommé en référence à Pluton, qui vient à la suite des planètes Uranus et Neptune dans le Système solaire. '),
(95, 95, 'Américium	', 'Am', '243,0614', 'L’américium est un élément radioactif de la famille des actinides. Sous forme métallique, il a une couleur blanche et un lustre argenté (plus argenté que le plutonium ou le neptunium). À température ambiante, il se ternit lentement dans l’air sec.  Du fait de son instabilité, l’américium n’est pas présent dans la croûte terrestre. C’est un élément artificiel produit lors de réactions successives intervenant dans le cœur des réacteurs nucléaires, et il est actuellement considéré comme un déchet radioactif.'),
(96, 96, 'Curium	', 'Cm', '247,0703', 'Le curium se présente comme un métal radioactif, d\'un blanc argenté et d\'une grande dureté. Il se forme dans les réacteurs nucléaires : une tonne de combustible usé en contient en moyenne 20 g.'),
(97, 97, 'Berkélium', 'Bk', '247,0703', 'Il a été synthétisé pour la première fois en décembre 1949 par Stanley G. Thompson, Le premier isotope produit a un nombre de masse de 243 et se dégrade avec une demi-vie de 4,5 heures. Dix autres isotopes ont été synthétisés depuis. En raison de sa rareté, le berkélium n\'a actuellement aucune utilisation commerciale.'),
(98, 98, 'Californium', 'Cf', '251,0796', 'Le californium trouve des applications comme amorce des réactions de fission dans les réacteurs nucléaires, dans le pilotage des centrales thermiques et des cimenteries en intervenant dans les sondes de contrôle de production, dans certaines radiothérapies, ainsi que dans l\'exploration pétrolière.'),
(99, 99, 'EsEinsteinium', 'Es', '252,0829', 'L\'einsteinium a été découvert en 1952 par Albert Ghiorso sous la forme de son isotope 253, récupéré dans les débris résultant d\'une explosion thermonucléaire. Il est produit en bombardant des actinides plus légers avec des neutrons.'),
(100, 100, 'Fermium', 'Fm', '257,0951', 'Seule une petite quantité de cet élément a été synthétisée. De ce fait, on ne sait encore que peu de choses de ses propriétés chimiques. Le fermium fut découvert par l\'équipe d\'Albert Ghiorso en 1952. Elle mit en évidence la présence de 255Fm dans les retombées de l\'explosion de la première bombe à hydrogène. '),
(101, 101, 'Mendélévium', 'Md', '258,0986', 'Cet élément hautement radioactif se forme par bombardement de l\'einsteinium par des noyaux d\'hélium 4. Le mendélévium a été dénommé en l\'honneur de Dmitri Mendeleïev, père du tableau périodique.'),
(102, 102, 'Nobélium', 'No', '259,1009', 'Le corps simple nobélium est un métal. Le nobélium a été découvert par l\'Institut Nobel de Physique à Stockholm et plus tard par Albert Ghiorso, Torbjørn Sikkeland (en), John R. Walton et Glenn Seaborg aux États-Unis en 1958. Il fut nommé nobélium en l\'honneur d\'Alfred Nobel3, chimiste suédois qui inventa la dynamite et fonda le prix Nobel. '),
(103, 103, 'Lawrencium', 'Lr', '260,1053', 'Il s\'agit d\'un élément synthétique observé pour la première fois le 14 février 1961 dans le Heavy Ion Linear Accelerator (HILAC) au Lawrence Radiation Laboratory de l\'université de Berkeley en bombardant une cible constituée de 3 mg de trois isotopes de californium par des ions de bore 10 et de bore 11.'),
(104, 104, 'Rutherfordium', 'Rf', '261,1087', 'Les chercheurs soviétiques avaient utilisé pour la synthèse une cible de plutonium bombardée par un faisceau d\'ions de néon 22 accélérés par un accélérateur linéaire5 d\'une énergie de 113-115 MeV. Ils annoncèrent qu\'ils avaient détecté une fission nucléaire en observant au microscope un verre spécial, ce qui indiquait pour eux la présence d\'un nouvel élément.'),
(105, 105, 'Dubnium', 'Db', '262,1138', 'L\'équipe américaine a synthétisé l\'élément en bombardant une cible de 249Cf par un faisceau d\'azote porté à 84 MeV au moyen d\'un accélérateur de particules. Ils ont obtenu le noyau 260105. Les atomes de l\'élément 105 furent détectés et confirmés le 5 mars 1970, bien que des indices semblent indiquer la formation à Berkeley de tels atomes l\'année précédente.'),
(106, 106, 'Seaborgium', 'Sg', '263,1182', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope connu le plus stable, le 269Sg, a une période radioactive d\'environ 3,1 min. Situé sous le tungstène dans le tableau périodique des éléments, il appartient au bloc d et présente les propriétés chimiques d\'un métal de transition.'),
(107, 107, 'Bohrium', 'Bh', '262,1229', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope connu le plus stable, le 270Bh, a une période radioactive d\'environ 1 min1. Situé sous le rhénium dans le tableau périodique des éléments, il appartient au bloc d et présente les propriétés chimiques d\'un métal de transition.'),
(108, 108, 'Hassium', 'Hs', '265', 'Le hassium 270 a été synthétisé pour la première fois, début 2007 par une équipe internationale sous la direction de chimistes de l\'Université Technique de Munich (Dr Alexander Yakushev, Chaire du Prof Türler à l\'Institut de radiochimie) et du Centre de recherche sur les ions lourds de Darmstadt. La synthèse du hassium 270 a réussi en bombardant du curium 248 pendant plusieurs semaines avec des ions de magnésium 26.'),
(109, 109, 'Meitnérium', 'Mt', '266', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope connu le plus stable, le meitnérium 278 (278Mt), a une période radioactive de 7,6 secondes. Situé sous l\'iridium dans le tableau périodique des éléments, le meitnérium appartient au bloc d et présente vraisemblablement les propriétés chimiques d\'un métal de transition.');
INSERT INTO `atomes` (`id`, `numero`, `nom`, `symbole`, `masse_atomique`, `presentation`) VALUES
(110, 110, 'Darmstadtium	', 'Ds', '269', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope connu le plus stable, le 281Ds, a une période radioactive d\'environ 9,6 s. Situé sous le platine dans le tableau périodique des éléments, il appartiendrait au bloc d et présenterait des propriétés chimiques de métal de transition. Il aurait en particulier des propriétés de métal noble1 et appartiendrait au groupe du platine'),
(111, 111, 'Roentgenium', 'Rg', '272', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope le plus stable, le 282Rg, a une période radioactive d\'environ 2,1 min. Situé sous l\'or dans le tableau périodique des éléments, il appartient au bloc d et serait un métal de transition, d\'autant qu\'il a été établi que le copernicium, qui lui fait suite sur la 7e période, présente clairement les propriétés d\'un métal de transition.'),
(112, 112, 'Copernicium', 'Cn', '277', 'Le copernicium a été synthétisé pour la première fois le 9 février 1996, à Darmstadt, en Allemagne, au GSI (Gesellschaft für Schwerionenforschung). Il a été obtenu en bombardant une cible de plomb 208 avec des ions de zinc 7011, lors d\'une expérience où un seul atome a été produit '),
(113, 113, 'Nihonium', 'Nh', '286', 'Il s\'agit d\'un transactinide très radioactif, dont l\'isotope connu le plus stable, le 286Nh, a une période radioactive de 19,6 s. Situé sous le thallium dans le tableau périodique des éléments, il est possible que ses propriétés chimiques, si elles pouvaient être étudiées, l\'apparentent à un métal pauvre.'),
(114, 114, 'Flérovium', 'Fl', '(289)', 'Le flérovium présenterait des affinités avec la famille des métaux pauvres, bien qu\'on ait initialement suspecté un comportement de gaz rare induit par une configuration électronique modifiée par des effets quantiques de couplage spin-orbite et d\'électrodynamique quantique.'),
(115, 115, 'Moscovium', 'Mc', '(288)', 'Dans la série de science-fiction de la fin des années 1990, Sept jours pour agir, le moscovium est un carburant d\'origine extraterrestre (récupéré sur le site du crash de Roswell) qui permet à l\'armée américaine d\'envoyer secrètement un être humain dans le passé pour annuler la survenue d\'une catastrophe.  En 1989, bien avant la découverte de ce nouvel élément, lors d\'un interview à Las Vegas, Bob Lazar annonçait avoir travaillé dans la base secrète du Nevada S4 proche de la Zone 51, sur un nouveau type de propulsion basé sur l\'élément chimique 115. Aucune preuve n\'a jamais été fournie.'),
(116, 116, 'Livermorium', 'Lv', '(293)', 'Il s\'agit d\'un transactinide très instable dont les quatre isotopes connus sont très radioactifs. Leur masse atomique est comprise entre 290 et 293, ce dernier nucléide ayant la période radioactive la plus longue des quatre, voisine de 60 ms. Dans le tableau périodique, il est situé sous les métaux pauvres, mais son appartenance à une famille d\'éléments chimiques n\'est pas établie.'),
(117, 117, 'Tennesse', 'Ts', '(291)', 'C\'est un transactinide très radioactif, dont l\'isotope connu le plus stable, le 294Ts, a une période radioactive d\'environ 51 ms. Situé sous l\'astate dans le tableau périodique des éléments, il appartient au bloc p et serait probablement de nature métallique7, plus précisément un métal pauvre.'),
(118, 118, 'Oganesson', 'Og', '294', 'Situé dans la continuité de la famille des gaz nobles, il serait chimiquement assez différent de ces derniers. Plutôt réactif, il pourrait former des composés, dont les propriétés de quelques-uns (tétrafluorure d\'oganesson OgF4 et difluorure d\'oganesson OgF2 par exemple) ont été calculées. Si on pouvait l\'étudier d\'un point de vue chimique, il se comporterait peut-être comme un métalloïde semi-conducteur en raison d\'une configuration électronique modifiée par couplage spin-orbite et des corrections dues à l\'électrodynamique quantique.');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `atomes`
--
ALTER TABLE `atomes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `atomes`
--
ALTER TABLE `atomes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=119;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
